// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkZRcN1hMSzExSEALiKkltxLDYlQfqqPU',
    appId: '1:580602368543:android:02acec176b1324bc3e7b2a',
    messagingSenderId: '580602368543',
    projectId: 'parkwell-ef505',
    databaseURL: 'https://parkwell-ef505-default-rtdb.firebaseio.com',
    storageBucket: 'parkwell-ef505.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-gX6XNIJVk7ycv2U0Gl746X3Jv76SlVA',
    appId: '1:580602368543:ios:ca8f3008e6b2d39b3e7b2a',
    messagingSenderId: '580602368543',
    projectId: 'parkwell-ef505',
    databaseURL: 'https://parkwell-ef505-default-rtdb.firebaseio.com',
    storageBucket: 'parkwell-ef505.appspot.com',
    iosClientId: '580602368543-t79kkef7n0osu9jsg4g19spanfo71vnd.apps.googleusercontent.com',
    iosBundleId: 'com.parkwell.customer',
  );
}
